import json

class AIProcessor:
    def __init__(self):
        # Mock AI processor for now
        pass
    
    def structure_question(self, raw_text: str, has_answer_key: bool = False):
        """Structure raw text into proper MCQ format"""
        # Return mock structured question
        return {
            "question_text": raw_text[:100] + "..." if len(raw_text) > 100 else raw_text,
            "options": [
                {"id": "A", "text": "Option A", "is_correct": True},
                {"id": "B", "text": "Option B", "is_correct": False},
                {"id": "C", "text": "Option C", "is_correct": False},
                {"id": "D", "text": "Option D", "is_correct": False}
            ],
            "predicted_answer": ["A"],
            "confidence_score": 0.85,
            "explanation": "This is a sample explanation generated by AI."
        }
    
    def generate_explanation(self, question: str, correct_answer: str):
        """Generate explanation for correct answer"""
        return f"Explanation for: {question}\nCorrect answer is {correct_answer} because..."

ai_processor = AIProcessor()